language: node_js
node_js:
  - 10.16.3

before_install:
  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypted_0c35eebf403c_iv -in quanht.pem.enc -out quanht.pem -d

deploy:
  - provider: script
    skip_cleanup: true
    script:
      - ssh -i quanht.pem -o StrictHostKeyChecking=no ubuntu@ec2-18-162-115-131.ap-east-1.compute.amazonaws.com 'bash -s' < deploy.sh
    on:
      branch: dev
branches:
  only:
    - dev

